###  Get info
get http://localhost:3001/info/

### Get all persons
get http://localhost:3001/api/persons

### Get known person
get http://localhost:3001/api/persons/1/

### Test for phonebook that isn't present in persons 
get http://localhost:3001/api/persons/10/

### Delete an entry that exists
delete http://localhost:3001/api/persons/2/

### Delete an entry that doesn't exist 
delete http://localhost:3001/api/persons/20/

### Add an entry for a phonebook
post http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "alice",
    "number" : "040-123456"
}

### Add an invalid entry for a phonebook
post http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number" : "jaohn"
}