### GET BLOGS 
GET http://localhost:3001/api/info

### GET BLOGS 
GET http://localhost:3001/api/blogs

### POST NEW BLOG 
POST http://localhost:3001/api/blogs/
content-type: application/json

{
  "title": "Blog 3",
  "author": "Authoer blog3",
  "url": "httpsBlogThreeeeee",
  "likes": 100
}
